// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlfJyOuapmdhLHjkibT_25olXED6sXaM',
    appId: '1:1076254256135:web:91dbc1979bd985f6320ea2',
    messagingSenderId: '1076254256135',
    projectId: 'trackexp-plus',
    authDomain: 'trackexp-plus.firebaseapp.com',
    storageBucket: 'trackexp-plus.firebasestorage.app',
    measurementId: 'G-9ZQHJY4L5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBac3yIeuDG2Vz6_IheXRFuSxK4VwWsheA',
    appId: '1:1076254256135:android:6d3382d662652a99320ea2',
    messagingSenderId: '1076254256135',
    projectId: 'trackexp-plus',
    storageBucket: 'trackexp-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0MDlu5-SZISB5hPxovJ0cTyvLDPWhqY',
    appId: '1:1076254256135:ios:6412e213622c9dd4320ea2',
    messagingSenderId: '1076254256135',
    projectId: 'trackexp-plus',
    storageBucket: 'trackexp-plus.firebasestorage.app',
    iosClientId: '1076254256135-gqkgnt9knk4u9kpjulcu2pgf30dnk7qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackexpPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0MDlu5-SZISB5hPxovJ0cTyvLDPWhqY',
    appId: '1:1076254256135:ios:6412e213622c9dd4320ea2',
    messagingSenderId: '1076254256135',
    projectId: 'trackexp-plus',
    storageBucket: 'trackexp-plus.firebasestorage.app',
    iosClientId: '1076254256135-gqkgnt9knk4u9kpjulcu2pgf30dnk7qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackexpPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlfJyOuapmdhLHjkibT_25olXED6sXaM',
    appId: '1:1076254256135:web:3b2c47364ad0cc58320ea2',
    messagingSenderId: '1076254256135',
    projectId: 'trackexp-plus',
    authDomain: 'trackexp-plus.firebaseapp.com',
    storageBucket: 'trackexp-plus.firebasestorage.app',
    measurementId: 'G-DW3NLZ7RFV',
  );
}
